// <auto-generated />
using System;
using ElectroLab.LearningApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ElectroLab.LearningApi.Migrations
{
    [DbContext(typeof(LearningDbContext))]
    partial class LearningDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ElectroLab.LearningApi.Data.Entities.LearnLabCriterion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LabelKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ParamsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UnitId", "SortOrder")
                        .IsUnique();

                    b.ToTable("learn_lab_criteria", (string)null);
                });

            modelBuilder.Entity("ElectroLab.LearningApi.Data.Entities.LearnLessonBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TitleKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UnitId", "SortOrder")
                        .IsUnique();

                    b.ToTable("learn_lesson_blocks", (string)null);
                });

            modelBuilder.Entity("ElectroLab.LearningApi.Data.Entities.LearnModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TitleKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("learn_modules", (string)null);
                });

            modelBuilder.Entity("ElectroLab.LearningApi.Data.Entities.LearnProgressRow", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.Property<bool>("LabPassed")
                        .HasColumnType("boolean");

                    b.Property<bool>("QuizPassed")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReadComplete")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SessionId", "UnitId");

                    b.HasIndex("UnitId");

                    b.ToTable("learn_progress", (string)null);
                });

            modelBuilder.Entity("ElectroLab.LearningApi.Data.Entities.LearnQuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectOptionId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("ExplanationKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromptKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UnitId", "SortOrder")
                        .IsUnique();

                    b.ToTable("learn_quiz_questions", (string)null);
                });

            modelBuilder.Entity("ElectroLab.LearningApi.Data.Entities.LearnUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExampleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("I18nKeyPrefix")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<int?>("NextUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NextUnitId");

                    b.HasIndex("ModuleId", "Slug")
                        .IsUnique();

                    b.ToTable("learn_units", (string)null);
                });

            modelBuilder.Entity("ElectroLab.LearningApi.Data.TranslationRow", b =>
                {
                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Locale", "Key");

                    b.ToTable("translations", (string)null);
                });

            modelBuilder.Entity("ElectroLab.LearningApi.Data.Entities.LearnLabCriterion", b =>
                {
                    b.HasOne("ElectroLab.LearningApi.Data.Entities.LearnUnit", "Unit")
                        .WithMany("LabCriteria")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ElectroLab.LearningApi.Data.Entities.LearnLessonBlock", b =>
                {
                    b.HasOne("ElectroLab.LearningApi.Data.Entities.LearnUnit", "Unit")
                        .WithMany("LessonBlocks")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ElectroLab.LearningApi.Data.Entities.LearnProgressRow", b =>
                {
                    b.HasOne("ElectroLab.LearningApi.Data.Entities.LearnUnit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ElectroLab.LearningApi.Data.Entities.LearnQuizQuestion", b =>
                {
                    b.HasOne("ElectroLab.LearningApi.Data.Entities.LearnUnit", "Unit")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ElectroLab.LearningApi.Data.Entities.LearnUnit", b =>
                {
                    b.HasOne("ElectroLab.LearningApi.Data.Entities.LearnModule", "Module")
                        .WithMany("Units")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectroLab.LearningApi.Data.Entities.LearnUnit", "NextUnit")
                        .WithMany()
                        .HasForeignKey("NextUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Module");

                    b.Navigation("NextUnit");
                });

            modelBuilder.Entity("ElectroLab.LearningApi.Data.Entities.LearnModule", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("ElectroLab.LearningApi.Data.Entities.LearnUnit", b =>
                {
                    b.Navigation("LabCriteria");

                    b.Navigation("LessonBlocks");

                    b.Navigation("QuizQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
